// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package facade

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

// Begin provides a mock function with given fields:
func (_m *MockTx) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolve provides a mock function with given fields: _a0, _a1
func (_m *MockTx) Resolve(_a0 *sql.Tx, _a1 *error) {
	_m.Called(_a0, _a1)
}
