// Code generated by mockery v2.9.4. DO NOT EDIT.

package facade

import (
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

// Begin provides a mock function with given fields:
func (_m *MockTxManager) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r2
}

// Resolve provides a mock function with given fields: _a0, _a2
func (_m *MockTxManager) Resolve(_a0 *sql.Tx, _a2 *error) {
	_m.Called(_a0, _a2)
}
